language: ruby

rvm:
  - 2.1.5

env:
  - DB=postgresql

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - cp config/database.travis.yml config/database.yml

script:
  - RAILS_ENV=test bundle exec rake db:create db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rspec
