language: ruby

rvm:
  - 2.1.5

addons:
  firefox: "33"

env:
  - DB=postgresql

before_install:
  - cp config/database.travis.yml config/database.yml

script:
  - RAILS_ENV=test bundle exec rake db:create db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rspec
